baseURL: 'https://hylu.dev'
languageCode: en-us
title: hylu blog
theme: ["PaperMod"]
enableRobotsTXT: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
markup:
  highlight:
    #anchorLineNos: true
    codeFences: true
    guessSyntax: false
    lineNos: false
    #noClasses: false
    style: onedark
params:
  footer:
    hideCopyright: false
  featuredProjects:
      - pageRef: projects/darkstar-showdown/
      - pageRef: projects/slime-hunter/
      - pageRef: projects/pianotypes/
      - pageRef: projects/bujots/
  featuredPosts:
    - pageRef: posts/2023/old/dev/basics-of-shader-fractals/
    - pageRef: posts/2023/old/dev/3d-matrix-rotations/
    - pageRef: osu_banner
    - pageRef: posts/2023/old/osu/osu_fanart/
    - pageRef: posts/2023/old/other/some-casual-art/
  customCSS: ["css/custom.css"]
  profileMode:
        enabled: true
        title: "Don't mind me." # optional default will be site title
        subtitle: "Just coding the worries away."
        imageUrl: "img/heart.svg" # optional
        imageTitle: "Heart" # optional
        imageWidth: 300 # custom size
        imageHeight: 300 # custom size
        imageLink: "/posts" # CUSTOM: index_profile
  socialIcons:
    - name: "github"
      url: "https://github.com/hylu-dev"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/roylu01/"
    - name: "cv"
      url: "https://hylu.dev/documents/resume.pdf"
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  defaultTheme: dark
  assets:
    favicon: "favicon.ico"
    disableHLJS: true
  cover:
    linkFullImages: true
  homeInfoParams:
    Title: "Don't mind me."
    Content: "Just stress writing."
menu:
  main:
    - name: posts
      pageRef: /posts
      weight: 10
    - name: archive
      pageRef: /archive
      weight: 20
    - name: search
      pageRef: /search
      weight: 30
    - name: tags
      pageRef: /tags
      weight: 40
