baseURL = 'https://hylog.netlify.app/'
languageCode = 'en-us'
title = 'Hylu Blog'
theme = 'PaperMod'

[params]
    ShowBreadCrumbs = true
    ShowPostNavLinks = true
[params.assets]
    favicon = "/favicon.ico"
[params.cover]
    linkFullImages = true
[params.homeInfoParams]
    Title = "Don't mind me."
    Content = "Just stress writing."

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
[[menu.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 40
