baseURL: 'https://hylog.netlify.app/'
languageCode: en-us
title: Hylu Blog
theme: PaperMod
disqusShortname: hylog
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
params:
  custom_css: ["css/custom.css"]
  profileMode:
        enabled: true
        title: "Don't mind me." # optional default will be site title
        subtitle: "Just stress writing."
        imageUrl: "img/heart.svg" # optional
        imageTitle: "Heart" # optional
        imageWidth: 320 # custom size
        imageHeight: 320 # custom size
        buttons:
            - name: Posts
              url: "/posts"
  socialIcons:
    - name: "github"
      url: "https://github.com/hylu-dev"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/roylu01/"
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  defaultTheme: dark
  assets:
    favicon: "favicon.ico"
  cover:
    linkFullImages: true
  homeInfoParams:
    Title: "Don't mind me."
    Content: "Just stress writing."
menu:
  main:
    - name: Posts
      pageRef: /posts
      weight: 10
    - name: Search
      pageRef: /search
      weight: 20
    - name: Tags
      pageRef: /tags
      weight: 30
