baseURL: 'https://hylu.dev'
languageCode: en-us
title: Hylu Blog
theme: ["PaperMod"]
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
markup:
  highlight:
    #anchorLineNos: true
    codeFences: true
    guessSyntax: false
    lineNos: false
    #noClasses: false
    style: onedark
params:
  featuredProjects:
      - pageRef: projects/darkstar-showdown/
        links:
          - name: "github"
            url: "https://github.com/hylu-dev/next-game"
      - pageRef: projects/pianotypes/
        links:
          - name: "github"
            url: "https://github.com/hylu-dev/pianotypes"
      - pageRef: projects/bujots/
        links:
            - name: "github"
              url: "https://github.com/hylu-dev/bujots"
      
  featuredPosts:
    - osu_banner
    - posts/2023/old/osu/osu_fanart/
    - posts/2023/old/other/some-casual-art/
  custom_css: ["css/custom.css"]
  profileMode:
        enabled: true
        title: "Don't mind me." # optional default will be site title
        subtitle: "Just coding the worries away."
        imageUrl: "img/heart.svg" # optional
        imageTitle: "Heart" # optional
        imageWidth: 300 # custom size
        imageHeight: 300 # custom size
        imageLink: "/posts" # CUSTOM: index_profile
  socialIcons:
    - name: "github"
      url: "https://github.com/hylu-dev"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/roylu01/"
    - name: "cv"
      url: "https://hylu.dev/documents/resume.pdf"
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  defaultTheme: dark
  assets:
    favicon: "favicon.ico"
    disableHLJS: true
  cover:
    linkFullImages: true
  homeInfoParams:
    Title: "Don't mind me."
    Content: "Just stress writing."
menu:
  main:
    - name: Posts
      pageRef: /posts
      weight: 10
    - name: Archive
      pageRef: /archive
      weight: 20
    - name: Search
      pageRef: /search
      weight: 30
    - name: Tags
      pageRef: /tags
      weight: 40
