baseURL: 'https://hylog.netlify.app/'
languageCode: en-us
title: Hylu Blog
theme: PaperMod
disqusShortname: hylog
params:
  profileMode:
        enabled: true
        title: "</empty>" # optional default will be site title
        subtitle: ""
        imageUrl: "img/heart.svg" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 320 # custom size
        imageHeight: 320 # custom size
        buttons:
            - name: Archive
              url: "/posts"
            - name: Github
              url: "https://github.com/hylu-dev"
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  defaultTheme: dark
  assets:
    favicon: "favicon.ico"
  cover:
    linkFullImages: true
  homeInfoParams:
    Title: "Don't mind me."
    Content: "Just stress writing."
menu:
  main:
    - name: Archive
      pageRef: /Posts
      weight: 10
    - name: Tags
      pageRef: /tags
      weight: 30
